image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install --quiet
  - npm --prefix ./functions install

build:
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - npm run build-prod


deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - npm run deploy-prod
  only:
    - master
