image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install --quiet
    - npm run build-prod
    - npm install -g firebase-tools
    - firebase use --add todo-app-fe --token $FIREBASE_TOKEN
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
