image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install --quiet

build:
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - npm run build-prod

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - npm install -g firebase-tools
    - firebase use --add todo-app-fe --token $FIREBASE_TOKEN
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - master
