image: node:latest
stages:
  - build
  - deploy

before_script:
  - npm install
  - npm --prefix ./functions install

build:
  stage: build
  script:
    - npm run build-prod

deploy:
  stage: deploy
  script:
    - npm run deploy
  only:
    - master
