image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install --quiet
  - npm --prefix ./functions install

build:
  stage: build
  artifacts:
    paths:
      - public/
  script:
    - ng build --prod

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - master
